### ISSUE TITLE
vars problem

### ISSUE THREAD

**Issue by LightningLoops** [LiveSplit/LiveSplit.ScriptableAutoSplit#23]
"'System.Dynamic.ExpandoObject' does not contain a definition for " error appears in Event Viewer when trying to use the vars object. Code that follows the vars line is skipped.

Weird thing is, it was working the day before, now it doesn't. Timer now doesn't reset, nor splits. Just starts.

**Comment by fatalis** [comment]
can you show your code?

**Comment by LightningLoops** [comment]
state("I Wanna Be The Boshy")
{
	byte area : 0x00059AB8, 0x0, 0x268, 0xA8;
}

init
{
	refreshRate = 50;
	
	vars.noSplitAreas = new bool[] 
	{
		true,true,true,true,
		false,false,true,false,
		false,true,false,false,
		false,false,false,false,
		true,false,true,true,
		true,true,false,true,
		false,false,false,false,
		true,true,true,false,
		false,true,true,false,
		true,true,false,true,
		true,true,true,true,
		true,true,true,false,
		true,true,true,true,
		true,true,true,true,
		true,true,true,false
	};
	
	vars.flags = new bool[60];
	
	Array.Copy(vars.noSplitAreas, vars.flags, 60);
}

start
{
	return (old.area == 2 && current.area == 36);
}

split
{
	if (old.area != current.area && !vars.flags[current.area])
	{
		vars.flags[current.area] = true;
		return true;
	}
}

reset
{
	if (current.area == 1 && old.area != 1)
	{
		Array.Copy(vars.noSplitAreas, vars.flags, 60);
		return true;
	}
}

isLoading
{
	return false;
}

**Comment by LightningLoops** [comment]
'System.Dynamic.ExpandoObject' does not contain a definition for 'flags'

   at CallSite.Target(Closure , CallSite , Object )
   at CompiledScript.Execute(LiveSplitState timer, Object old, Object current, Object vars, Process game)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute6[T0,T1,T2,T3,T4,T5,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5)
   at CallSite.Target(Closure , CallSite , Object , LiveSplitState , ExpandoObject , ExpandoObject , ExpandoObject , Process )
   at LiveSplit.ASL.ASLMethod.Run(LiveSplitState timer, ASLState old, ASLState current, ExpandoObject vars, Process game, String& version, Double& refreshRate)
   at LiveSplit.ASL.ASLScript.runMethod(ASLMethod methodToRun, LiveSplitState lsState, String& ver)
   at LiveSplit.ASL.ASLScript.RunUpdate(LiveSplitState lsState)
   at LiveSplit.UI.Components.Component.UpdateScript(LiveSplitState state)

**Comment by fatalis** [comment]
it's working fine for me (as far as I can tell) and the code looks fine, so I have no idea. make sure you've loaded the correct file?

**Comment by fatalis** [comment]
the only thing I can think of is Array.Copy not playing nice with ExpandoObject, but I highly doubt that's the problem. worth a try if nothing else works for you though.

**Comment by LightningLoops** [comment]
Well, since the simple attribution with vars.flags doesn't execute as well, I don't think that's the problem, but I'll consider it, thanks.

Anyway, I opened LiveSplit and the game now, and it works, just like you said. The other day this happened to me too. I wanted to upload this so people could download it directly, but I'm kinda on the fence. What should I do? Are there updates for auto splitters that are uploaded?

**Comment by fatalis** [comment]
ASL scripts are downloaded every time and aren't stored, so they're always up to date.

**Comment by LightningLoops** [comment]
That's cool, didn't know that. 

I was wondering, is there a way to create variables, arrays, etc in ASL, accesible to the entire script, without using the vars object?

**Comment by fatalis** [comment]
no, not currently. you can make a C# component if you need more flexibility though

**Comment by LightningLoops** [comment]
Well, I'm not familiar with that. You see, I just know the logic. I don't even know C# much; had to look up some things. But I came across something that might solve the vars problem:
http://www.heartysoft.com/ashic/blog/2010/5/anonymous-types-c-sharp-4-dynamic

As they state, the only thing that should be done is adding one line to AssemblyInfo.cs:
[assembly:InternalsVisibleTo("DynamicTest")]

Which I believe to be this file here:
https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/blob/master/Properties/AssemblyInfo.cs

What are your thoughts? Is it worth risking?

**Comment by fatalis** [comment]
that's not related to the issue you're having.

**Comment by LightningLoops** [comment]
Ok. Thank you.
