### ISSUE TITLE
Unable to load any ASL script with dev version

### ISSUE THREAD

**Issue by ROMaster2** [LiveSplit/LiveSplit.ScriptableAutoSplit#47]
```
Exception thrown: 'System.InvalidCastException' in LiveSplit.ScriptableAutoSplit.dll
LiveSplit.exe Error: 0 : Specified cast is not valid.

   at LiveSplit.ASL.ASLParser.<>c.<Parse>b__0_5(ParseTreeNode x) in C:\Git\LiveSplit\LiveSplit\Components\LiveSplit.ScriptableAutoSplit\ASL\ASLParser.cs:line 54
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at LiveSplit.ASL.ASLParser.Parse(String code) in C:\Git\LiveSplit\LiveSplit\Components\LiveSplit.ScriptableAutoSplit\ASL\ASLParser.cs:line 54
   at LiveSplit.UI.Components.ASLComponent.LoadScript() in C:\Git\LiveSplit\LiveSplit\Components\LiveSplit.ScriptableAutoSplit\Component.cs:line 154
   at LiveSplit.UI.Components.ASLComponent.UpdateScript() in C:\Git\LiveSplit\LiveSplit\Components\LiveSplit.ScriptableAutoSplit\Component.cs:line 119
```

Any script that's loaded gives the same error.

**Comment by ROMaster2** [comment]
Changing lines 54 and 55 to:
```
                    var module_base = child_nodes[4].ChildNodes.Select(x => Convert.ToInt64(x.Token.Value)).First();
                    var offsets = child_nodes[4].ChildNodes.Skip(1).Select(x => Convert.ToInt64(x.Token.Value)).ToArray();
```
Seemed to have fixed the problem. I'd make a push but am checking to see if you'd prefer a better solution.

**Comment by CryZe** [comment]
Can you try to figure out which commit introduced the need for this change?

**Comment by ROMaster2** [comment]
Immediately I suspect the change from 32 integers to 64, but I'll look deeper to see if that's the actual cause.

**Comment by ROMaster2** [comment]
Seems to be the case. Using `(int)` works if https://github.com/LiveSplit/LiveSplit/blob/master/LiveSplit/LiveSplit.Core/ComponentUtil/DeepPointer.cs#L13 is reverted back to `using OffsetT = Int32;`.

**Comment by CryZe** [comment]
The problem is that the actual pointers are being casted to int64. Since it's signed, the pointers are sign extended, which completely messes them up when interpreted as an unsigned address. So that should probably a zero extend instead (unsigned cast)

**Comment by res0nance** [comment]
My guess at the reasoning would be if the program was compiled 32-bits IntPtr would be 4 bytes. I'm not certain if this would affect its ability to handle 64-bit games

**Comment by wooferzfg** [comment]
https://github.com/LiveSplit/LiveSplit/commit/da76ca8d18cb3ef1369e4276348e5c85f2439404
https://github.com/LiveSplit/LiveSplit.ScriptableAutoSplit/commit/7e5a6cbe91569e7688fdb37446d32326b4b14b1c
